language: java
jdk:
- openjdk8
- openjdk11
- openjdk13

install:
- git clone https://github.com/mjw99/jquante.git ; cd jquante ; mvn clean install ; cd ..

script:
- mvn clean package ; java -jar ./target/benchmarks.jar
